# -*- coding: utf-8 -*-
import re

re_urls = re.compile(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
re_hastag = re.compile(r'\#[0-9a-zA-Z]+')
re_tuser = re.compile(r'@[a-zA-Z0-9_]+')

class LimpiadorTweets(object):
	
	@staticmethod
	def clean(line):
		line = line.lower()
		line = line.replace("\n", ". ").replace("\r", ". ").replace(u"\u0085", ". ").replace(u"\u2028", ". ").replace(u"\u2029", ". ")
		line = re_urls.sub(" URL ", line)
		line = re_hastag.sub(" HASTAG ", line)
		line = re_tuser.sub(" USER ", line)
		line = line.replace("?", " QUESTION ")
		line = line.replace(u"¿", " QUESTION ")
		line = line.replace("!", " EXCLAMATION ")
		line = line.replace("...", " DOTDOTDOT ")
		#line = line.replace(".", " DOT ")
		#line = line.replace(",", " COMMA ")
		line = line.replace(".", " ")
		line = line.replace(",", " ")
		line = line.replace("/", " ")
		line = line.replace("\\", " ")
		line = line.replace("\"", " ")
		line = line.replace("-", " ")
		line = line.replace(")", " ")
		line = line.replace("(", " ")
		line = line.replace("'", " ")
		line = line.replace(":", " ")
		line = line.replace(u"’", " ")
		line = line.replace(u"‘", " ")
		line = line.replace("+", " ")
		line = line.replace("_", " ")
		line = line.replace(u"´", " ")
		line = line.replace(u"`", " ")
		line = line.replace(u"", " ")
		line = line.replace(u"", " ")
		line = line.replace(u"", " ")
		line = line.replace(u"", " ")
		line = line.replace(u"«", " ")
		line = line.replace(u"»", " ")
		line = line.replace(u"“", " ")
		line = line.replace(u"”", " ")
		line = line.replace(u"¨", " ")
		line = line.replace(u"á", "a")
		line = line.replace(u"é", "e")
		line = line.replace(u"í", "i")
		line = line.replace(u"ó", "o")
		line = line.replace(u"ú", "u")
		line = line.replace(u"ü", "u")
		line = line.replace(u"ñ", "n")
		line = line.replace(u"…", " ")
		line = line.replace("http", " ")
		line = line.replace("https", " ")
		line = line.replace("  ", " ")
		line = line.replace("  ", " ")
		line = line.replace("  ", " ")
		line = line.replace("  ", " ")


		return line